version: "3"

services:

  db:
    image: "mysql"
    # command: --default-authentication-plugin=mysql_native_password
    container_name: db_lab
   
    restart: always
    environment:
      MYSQL_DATABASE: lge
      MYSQL_ROOT_PASSWORD: 'PASSWORD'
      #MYSQL_USER: 'user'
      #MYSQL_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dblab:/var/lib/mysql
  
  admin:
    image: 'phpmyadmin'
    container_name: admincontainer
    restart: always
    ports:
      - 8080:80
    expose:
      - '8080'
    depends_on:
      - db

volumes:
  dblab:
  
  # backend:
  #   build: .
  #   container_name: backendserver
  #   restart: always
  #   depends_on:
  #     - db
